#!/bin/bash
MY_PATH="`dirname \"$0\"`"
cd "$MY_PATH"
HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="Creado por: Elsoberanox - https://www.youtube.com/c/JuegosenLinux"
TITLE="www.juegosenlinux.site"
MENU="CupHead - Elsoberanox"

OPTIONS=(1 "Instalar CupHead"
         2 "Desinstalar"
         3 "Ver mas ports"
         4 "Salir")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
#!/bin/bash
MY_PATH="`dirname \"$0\"`"
cd "$MY_PATH"
sudo cp winetricks /usr/bin/
wget https://archive.org/download/matawinbugs/matawinbugs.sh
sudo chmod +x matawinbugs.sh
sudo mv matawinbugs.sh /usr/bin/
sudo chmod +x badown
wget https://archive.org/download/wineson.7z_202110/wineson.7z
7z x wineson.7z
sudo rm -R wineson.7z
sudo mv wineson /opt/
./badown http://www.mediafire.com/file/dbt5h545l4zvm4j/cuphead.rar/file
unrar x cuphead.rar
sudo rm -R cuphead.rar
mkdir $HOME/Juegos/
export WINEARCH=win64 WINEPREFIX=$HOME/Juegos/Cuphead
export PATH=/opt/wineson/bin/
wine setup_cuphead_20170929_\(15295\).exe
export PATH=/usr/bin
matawinbugs.sh
echo -e "cd $HOME/Juegos/Cuphead/drive_c/GOG\ Games/Cuphead/\nexport PATH=/opt/wineson/bin/\nwine Cuphead.exe" >> cuphead-bin
sudo chmod +x cuphead-bin
sudo mv cuphead-bin /usr/bin/
wget https://archive.org/download/cupheadico/cupheadico.png
sudo mv cupheadico.png /opt/
echo -e "[Desktop Entry]\n Version=1.0\n Type=Application\n Name=CupHead Linux\n Comment=Cuphead-bin\n Icon=/opt/cupheadico.png\n Exec=cuphead-bin\n Categories=Game;" >> CupHead.desktop
sudo chmod +x CupHead.desktop
sudo mv CupHead.desktop $HOME/.local/share/applications
xdg-desktop-menu forceupdate

            ;;
        2)
sudo rm -R /usr/bin/winetricks
sudo rm -R /opt/wineson
sudo rm -R /usr/bin/cuphead-bin
sudo rm -R /opt/cupheadico.png
sudo rm -R $HOME/Juegos/Cuphead
sudo rm -R $HOME/.local/share/applications/CupHead.desktop
xdg-desktop-menu forceupdate

            ;;
        3)
            xdg-open https://www.juegosenlinux.site/
            ;;
            
                    3)
            exit
            ;;
esac
